// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TransactionCategory = "salary" | "freelance" | "interest" | "dividend" | "refund" | "housing" | "groceries" | "transport" | "dining" | "entertainment" | "health" | "education" | "shopping" | "utilities" | "subscriptions" | "travel" | "fitness" | "transfer" | "investment" | "fees" | "insurance" | "other";
