// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountType } from "../../backend/bindings/AccountType";

export type Account = { unid: string, user_unid: string, account_number: string, iban: string | null, label: string, account_type: AccountType, balance: number, currency: string, closed_at: string | null, created_at: string, updated_at: string, };
