// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BugType } from "./BugType";

export type AddBugReport = { bug_type: BugType, message: string, exception_message: string | null, stack_trace: string | null, user_login: string | null, url: string | null, user_agent: string | null, application: string | null, };
