// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One point in the balance-over-time line chart: running balance at end of each day.
 */
export type BalanceHistoryRow = { day: string, balance: number, };
