// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DepositSource } from "./DepositSource";

export type CreateDepositRequest = { to_account_unid: string, source: DepositSource, source_name: string, source_iban: string | null, amount: number, description: string | null, };
