// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateTransferRequest = { from_account_unid: string, 
/**
 * Set for "send to saved recipient" or manual recipient flows.
 */
to_recipient_unid: string | null, 
/**
 * Set for "transfer between own accounts" flow.
 */
to_account_unid: string | null, amount: number, description: string | null, reference: string | null, };
