// This file is generated by ts-rs. Do not edit this file manually.

export type CreateTransferRequest = {
  from_account_unid: string;
  to_recipient_unid: string | null;
  to_account_unid: string | null;
  amount: number;
  description: string | null;
  reference: string | null;
};
