// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateInvoiceRequest = { recipient_name: string, recipient_email: string | null, recipient_iban: string | null, description: string | null, amount: number, currency: string, due_date: string | null, notes: string | null, };
