// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregate stats for the dashboard stats row (last N days) .
 */
export type DashboardStatsRow = { tx_count: number, total_spent: number, total_received: number, };
