// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One slice in the spending-breakdown donut chart.
 */
export type DonutStatRow = { category: string, total: number, };
