// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvoiceStatus } from "../../backend/bindings/InvoiceStatus";

export type Invoice = { unid: string, user_unid: string, invoice_number: string, recipient_name: string, recipient_email: string | null, recipient_iban: string | null, description: string | null, amount: number, currency: string, status: InvoiceStatus, due_date: string | null, notes: string | null, created_at: string, updated_at: string, };
