// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the money-flow chart: income vs expenses for a single day.
 */
export type MoneyFlowRow = { date: string, income: number, expense: number, };
