// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoleAccessWithUser = { unid: string, role: string, user_email: string, user_unid: string, };
