// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionCategory } from "../../backend/bindings/TransactionCategory";
import type { TransactionStatus } from "../../backend/bindings/TransactionStatus";
import type { TransactionType } from "../../backend/bindings/TransactionType";

export type Transaction = { unid: string, account_unid: string, transaction_type: TransactionType, description: string, category: TransactionCategory, amount: number, currency: string, counterparty_name: string | null, counterparty_iban: string | null, reference: string | null, status: TransactionStatus, created_at: string, };
