// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateProfileRequest = { first_name: string | null, last_name: string | null, date_of_birth: string | null, phone: string | null, country: string | null, city: string | null, address: string | null, postal_code: string | null, avatar_data: string | null, };
