/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DashboardWalletsRouteImport } from './routes/dashboard/wallets'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardTransactionsRouteImport } from './routes/dashboard/transactions'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardRecipientsRouteImport } from './routes/dashboard/recipients'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard/messages'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard/invoices'
import { Route as DashboardHelpRouteImport } from './routes/dashboard/help'
import { Route as DashboardBugreportsRouteImport } from './routes/dashboard/bugreports'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardAccessDemoRouteImport } from './routes/dashboard/access-demo'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminBugreportsRouteImport } from './routes/admin/bugreports'
import { Route as AccountProfileRouteImport } from './routes/account/profile'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DashboardWalletsRoute = DashboardWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRecipientsRoute = DashboardRecipientsRouteImport.update({
  id: '/recipients',
  path: '/recipients',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBugreportsRoute = DashboardBugreportsRouteImport.update({
  id: '/bugreports',
  path: '/bugreports',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccessDemoRoute = DashboardAccessDemoRouteImport.update({
  id: '/access-demo',
  path: '/access-demo',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBugreportsRoute = AdminBugreportsRouteImport.update({
  id: '/bugreports',
  path: '/bugreports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/bugreports': typeof AdminBugreportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/access-demo': typeof DashboardAccessDemoRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/bugreports': typeof DashboardBugreportsRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/recipients': typeof DashboardRecipientsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/wallets': typeof DashboardWalletsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/bugreports': typeof AdminBugreportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/access-demo': typeof DashboardAccessDemoRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/bugreports': typeof DashboardBugreportsRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/recipients': typeof DashboardRecipientsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/wallets': typeof DashboardWalletsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/bugreports': typeof AdminBugreportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/access-demo': typeof DashboardAccessDemoRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/bugreports': typeof DashboardBugreportsRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/recipients': typeof DashboardRecipientsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/wallets': typeof DashboardWalletsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/account/profile'
    | '/admin/bugreports'
    | '/admin/users'
    | '/dashboard/access-demo'
    | '/dashboard/analytics'
    | '/dashboard/bugreports'
    | '/dashboard/help'
    | '/dashboard/invoices'
    | '/dashboard/messages'
    | '/dashboard/recipients'
    | '/dashboard/settings'
    | '/dashboard/transactions'
    | '/dashboard/users'
    | '/dashboard/wallets'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/account/profile'
    | '/admin/bugreports'
    | '/admin/users'
    | '/dashboard/access-demo'
    | '/dashboard/analytics'
    | '/dashboard/bugreports'
    | '/dashboard/help'
    | '/dashboard/invoices'
    | '/dashboard/messages'
    | '/dashboard/recipients'
    | '/dashboard/settings'
    | '/dashboard/transactions'
    | '/dashboard/users'
    | '/dashboard/wallets'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/account/profile'
    | '/admin/bugreports'
    | '/admin/users'
    | '/dashboard/access-demo'
    | '/dashboard/analytics'
    | '/dashboard/bugreports'
    | '/dashboard/help'
    | '/dashboard/invoices'
    | '/dashboard/messages'
    | '/dashboard/recipients'
    | '/dashboard/settings'
    | '/dashboard/transactions'
    | '/dashboard/users'
    | '/dashboard/wallets'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/dashboard/wallets': {
      id: '/dashboard/wallets'
      path: '/wallets'
      fullPath: '/dashboard/wallets'
      preLoaderRoute: typeof DashboardWalletsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/transactions': {
      id: '/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/recipients': {
      id: '/dashboard/recipients'
      path: '/recipients'
      fullPath: '/dashboard/recipients'
      preLoaderRoute: typeof DashboardRecipientsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/help': {
      id: '/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/bugreports': {
      id: '/dashboard/bugreports'
      path: '/bugreports'
      fullPath: '/dashboard/bugreports'
      preLoaderRoute: typeof DashboardBugreportsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/access-demo': {
      id: '/dashboard/access-demo'
      path: '/access-demo'
      fullPath: '/dashboard/access-demo'
      preLoaderRoute: typeof DashboardAccessDemoRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bugreports': {
      id: '/admin/bugreports'
      path: '/bugreports'
      fullPath: '/admin/bugreports'
      preLoaderRoute: typeof AdminBugreportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRouteRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountProfileRoute: typeof AccountProfileRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountProfileRoute: AccountProfileRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminBugreportsRoute: typeof AdminBugreportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBugreportsRoute: AdminBugreportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardAccessDemoRoute: typeof DashboardAccessDemoRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBugreportsRoute: typeof DashboardBugreportsRoute
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardRecipientsRoute: typeof DashboardRecipientsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardWalletsRoute: typeof DashboardWalletsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAccessDemoRoute: DashboardAccessDemoRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBugreportsRoute: DashboardBugreportsRoute,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardRecipientsRoute: DashboardRecipientsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardWalletsRoute: DashboardWalletsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
